[package]
name = "consensus"
version = "0.0.1"
description = "Pure Rust implementation of Bitcoin consensus"
authors = ["Oleg Andreev <oleganza@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
